package controller;

import javafx.concurrent.ScheduledService;
import javafx.concurrent.Task;
import javafx.util.Duration;
import model.animals.ChuQuangLuong;
import model.animals.Cow;
import model.animals.Fish;
import model.animals.Pig;
import model.animals.Wolf;
import model.block.BlockModel;
import model.block.BlockFactory;
import model.entity.EntityFactory;
import model.entity.EntityModel;
import model.generation.*;
import model.world.WorldModel;
import view.audio.SoundEngine;
import view.block.BlockTextureMap;
import view.WorldView;
import view.entity.EntityTextureMap;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Queue;
import java.util.Random;
import java.util.Set;
import java.util.concurrent.ConcurrentLinkedQueue;

/**
 * Controls everything
 */
public class WorldController {
    private final Queue<EntityModel> waitToSpawn;
    public static int WORLD_TILE_SIZE = 16;
    public static WorldController controller;
    private final Map<String, Path> texturePath;
    private String currentTexture;

    public static WorldController getController() {
        if(controller == null) {
            controller = new WorldController();
        }
        return controller;
    }

    public void setWorldModel(WorldModel worldModel) {
        this.worldModel = worldModel;
    }

    public void setWorldView(WorldView worldView) {
        this.worldView = worldView;
    }

    public WorldModel getWorldModel() {
        return worldModel;
    }

    WorldModel worldModel;
    WorldView worldView;
    Random random = new Random();

    // Update world in a separate thread.
    // ScheduledService is used to define a task that is run periodically
    // The Object is declared with the use of anonymous class.
    // (I use this syntax because I'm lazy, might change to concrete class in the future)
    // Reference for anonymous class: https://dev.java/learn/classes-objects/nested-classes/#anonymous
    // Reference for ScheduledService: https://openjfx.io/javadoc/26/javafx.graphics/javafx/concurrent/ScheduledService.html
    private final ScheduledService<Object> updateWorldService = new ScheduledService<Object>() {
        @Override
        protected Task<Object> createTask() {
            return new Task<Object>() {
                @Override
                protected Object call() throws Exception {
//                    updateWorld();
                    refreshEntityViews();
                    worldModel.update();
                    playSoundEvents();
                    while(!waitToSpawn.isEmpty()) {
                        spawnEntity(waitToSpawn.poll());
                    }
                    return null;
                }
            };
        }
    };

    private WorldController(){
        waitToSpawn = new ConcurrentLinkedQueue<>();
        texturePath = new LinkedHashMap<>();
        texturePath.put("basic", Path.of("assets/basic"));
        texturePath.put("minecraft", Path.of("assets/minecraft_based"));
        texturePath.put("homemade", Path.of("assets/homemade"));

    }

    /**
     * Start updating the world
     * @param tps: Tick speed
     */
    public void startUpdateWorldService(long tps) {
        updateWorldService.setPeriod(Duration.seconds(1.0/tps));
        updateWorldService.start();
    }

    public void stopUpdateWorldService() {
        updateWorldService.cancel();
    }

    /**
     * Remove views for dead entities
     */
    private void refreshEntityViews(){
        worldModel.getDeadEntities().forEach(
                entityModel -> {
                    worldView.getAllEntitiesView().removeView(entityModel);
                    SoundEngine.getEngine().playSound(entityModel.getEntityType() + "_death");
                }
        );
    }

    private void playSoundEvents(){
        if(worldModel.getEntities().stream()
                .anyMatch(entityModel ->
                                  entityModel instanceof Wolf wolf && wolf.hasJustAttacked())){
            SoundEngine.getEngine().playSound("wolf_eat");
        }
        worldModel.getEntities().forEach(
                entityModel -> {
                    if(random.nextDouble() < 0.001) {
                        SoundEngine.getEngine().playSound(entityModel.getEntityType()+"_idle");
                    }
                }
        );
    }

    public void registerBlockTextures(){
        BlockTextureMap blockTextureMap = BlockTextureMap.loadFrom(Path.of("assets/minecraft_based"));
        worldView.getTerrainView().setTextureMap(blockTextureMap);
    }

    public void registerEntityTextures(){
//        EntityTextureMap entityTextureMap = new EntityTextureMap();
//        // temporary values generated by Claude, kind of derpy, might change later
//        entityTextureMap.registerEntity("pig",
//                                        Paths.get("assets/minecraft_based/pig.png"), 1,1.2, 0.9);
//        entityTextureMap.registerEntity("wolf",
//                                        Paths.get("assets/minecraft_based/wolf.png"),1, 1.5, 0.8
//        );
//
//        entityTextureMap.registerEntity("cow",
//                                        Paths.get("assets/minecraft_based/calf.png"),0, 1.2, 0.75
//        );
//
//        entityTextureMap.registerEntity("cow",
//                                        Paths.get("assets/minecraft_based/cow.png"),1, 2.4, 1.5
//        );
        EntityTextureMap entityTextureMap = EntityTextureMap.loadFrom(Paths.get("assets/minecraft_based"));
        worldView.getAllEntitiesView().setEntityTextureMap(entityTextureMap);
    }

    public void registerSound(){
        SoundEngine soundEngine = SoundEngine.getEngine();
        soundEngine.registerSound("grass_step", Paths.get("assets/audio/grass1.mp3"));
        soundEngine.registerSound("wolf_eat", Paths.get("assets/audio/wolf/growl1.mp3"));
        soundEngine.registerSound("pig_idle", Paths.get("assets/audio/pig/pig_idle.mp3"));
        soundEngine.registerSound("cow_idle", Paths.get("assets/audio/cow/idle.mp3"));
        soundEngine.registerSound("wolf_idle", Paths.get("assets/audio/wolf/bark.mp3"));
        soundEngine.registerSound("wolf_death", Paths.get("assets/audio/wolf/death.mp3"));
        soundEngine.registerSound("pig_death", Paths.get("assets/audio/pig/death.mp3"));
        soundEngine.registerSound("cow_death", Paths.get("assets/audio/cow/death.mp3"));
    }

    /**
     * Attempt to place a new block in the world
     * @param block The type of block be cloned and place
     * @param xPos The x position to place block, 0 <= x < world's width
     * @param yPos The y position to place block, 0 <= y < world's length
     */
    public void placeBlock(BlockModel block, int xPos, int yPos) {
        if(block == null) return;
        if(xPos < 0 || yPos < 0) return; // invalid coordinate
        if(xPos >= worldModel.getWidth() || yPos >= worldModel.getLength()) return;
        BlockModel newBlock = null;
        try {
            newBlock = BlockFactory.create(block.getBlockType(), xPos, yPos);
        }
        catch(Exception e) {
            IO.println("Exception when trying to place block: " + e.getMessage());
        }
        if(newBlock != null){
            worldModel.placeBlock(newBlock);
        }
    }

    /**
     * Spawn new Entity in the world
     * @param entity Entity to spawn
     */
    public void spawnEntity(EntityModel entity) {
        if(entity == null) {
            IO.println("Attempt to spawn null entity!");
            return;
        }
        worldModel.getEntities().add(entity);
//        worldView.getAllEntitiesView().addView(entity);
        worldView.getAllEntitiesView().requestRender(entity);
        IO.println("Spawned new " + entity.getEntityType() + ".");
    }

    public void requestSpawnEntity(EntityModel entity) {
        if(entity == null) return;
        waitToSpawn.add(entity);
    }

    public void registerBlocksAndEntities(){
        BlockFactory.register("cobble_stone", CobbleStoneBlock::new);
        BlockFactory.register("dirt", DirtBlock::new);
        BlockFactory.register("grass", GrassBlock::new);
        BlockFactory.register("mud", MudBlock::new);
        BlockFactory.register("sand", SandBlock::new);
        BlockFactory.register("sapling", SaplingBlock::new);
        BlockFactory.register("seed", SeedBlock::new);
        BlockFactory.register("tree", TreeBlock::new);
        BlockFactory.register("water", WaterBlock::new);
        BlockFactory.register("wood", WoodBlock::new);
        EntityFactory.register("cow", Cow::new);
        EntityFactory.register("chuquangluong", ChuQuangLuong::new);
        EntityFactory.register("fish", Fish::new);
        EntityFactory.register("pig", Pig::new);
        EntityFactory.register("wolf", Wolf::new);

    }

    public void setTexturePath(String name){
        if("home_graphic".equals(name)){
            name = "homemade";
        }
        if(texturePath.containsKey(name)){
            currentTexture = name;
            Path path = texturePath.get(name);
            worldView.getTerrainView().setTextureMap(BlockTextureMap.loadFrom(path));
            worldView.getAllEntitiesView().setEntityTextureMap(EntityTextureMap.loadFrom(path));
        }

    }

    public String getCurrentTextureMode() {
        return currentTexture;
    }

    public Set<String> getTextureModes() {
        return texturePath.keySet();
    }
    private double zoomFactor = 1.0;

    public double getZoomFactor() {
        return zoomFactor;
    }

    public void setZoomFactor(double zoomFactor) {
        this.zoomFactor = zoomFactor;
    }
    public WorldView getWorldView() {
        return worldView;
    }

}
